server:
  #端口号
  port: 8899
spring:
  datasource:
    url: jdbc:mysql://175.24.199.42:13306/stock?characterEncoding=utf-8
    username: fijon
    password: xu@db@920630
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      jdbc:
          batch_size: 500
          batch_versioned_data: true
      order_inserts: true
      order_updates: true
      ddl-auto: update
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
